### ISSUE TITLE
Lores of items get deleted

### ISSUE THREAD

**Issue by DontNeedAName** [Phoenix616/InventoryGui#16] opened 2020-12-27 23:18 UTC
When adding a lore to an ItemStack of an StaticGuiElement (not sure about other elements, haven't tested yet), the lore will not be displayed in the inventory. No matter how many lines it has.
I'm not sure what's causing this, but it must be something in the InventoryGUI#setItemText() method. In one else block it sets the lores to null and i'm not sure why it should. If i remove this block, everything is working fine. But I don't think this is a good solution.

**Comment by Phoenix616** [comment] 2020-12-27 23:27
This is kinda intended behaviour, you are supposed to specify the text of the element via an element's text property (e.g. via the [setter](https://docs.phoenix616.dev/inventorygui/de/themoep/inventorygui/StaticGuiElement.html#setText(java.lang.String...))), not via the item display name/lore manually.

Maybe changing it so that if the text is empty it will directly use whatever is on the item might be a good addition, I'll have to look into that. (Or feel free to do so and open a PR :))

For now if your goal is to display real items then I suggest not using the StaticGuiElement but directly using your own GuiElement which just copies all the properties from your item directly.

**Comment by DontNeedAName** [comment] 2020-12-28 22:52
I'm not sure if I should put the check directly into the setItemText() method, because that would make it kinda useless. The problem with checking before executing the method is that I can only check if the item has a display name or a lore. If I check for both it will cause issues because the method overrides both of them. I would need to have to different methods for setting display name and lore for that to work.
I want to check for display name too to try to implement this properly. Might be unnecessary. I'm not sure.

**Comment by Phoenix616** [comment] 2020-12-29 00:59
I took a look at the code and as far as I can tell `setItemText` already does everything required to preserve the original display name/lore by checking if no text is set before trying to apply it to the item.

If that's so what's happening for you then please provide some code examples which are broken.

**Comment by DontNeedAName** [comment] 2020-12-29 22:35
`
                if (lines.length > 1) {
                    meta.setLore(Arrays.asList(Arrays.copyOfRange(lines, 1, lines.length)));
                } else {
                    meta.setLore(null);
                }
`
If there's a lore set within the item, it uses that lore and if not it set's the lore to null. I think it might actually be the best idea to just remove the line setting it to null. This is also why the issue only affects lores and not titles. Titles don't get set to null when they're not set from the constructor.

**Comment by Phoenix616** [comment] 2020-12-30 00:18
The previous [`if (item != null && text != null && text.length > 0)`](https://github.com/Phoenix616/InventoryGui/blob/master/src/main/java/de/themoep/inventorygui/InventoryGui.java#L1088) should already prevent that block being entered though?

**Comment by DontNeedAName** [comment] 2020-12-31 11:48
I don't exactly understand how the code below works, but that block checks for text.lenght, not lines.length.

**Comment by Phoenix616** [comment] 2020-12-31 13:44
Yes, the `text` variable there is whatever someone sets the `text` field of the GuiElement to. By default that will be empty so no meta/lore is changed unless someone specifically sets the text of the element to something.

The creation of the lines array is just to make sure that a) all null objects are removed from the text array and b) that no array string entry contains new line but that every line is on its own.

**Comment by DontNeedAName** [comment] 2021-01-01 11:09
Yeah, but doesn't that change the length?

**Comment by Phoenix616** [comment] 2021-01-01 14:21
The `lines` variable will have the same length as there are lines in the full text array, yes. It will obviously not reduce the length to 0 if there already were lines in it before.

If you are actually seeing lore lines getting deleted then the error is most likely someone else and you should provide some example code that results in such behaviour.

**Comment by Phoenix616** [comment] 2021-04-21 17:23
Closing this due to it not being reproducible. If you have code causing this, please provide it.

**Closed** 2021-04-21 17:23 UTC
